[log]
level="INFO"    #INFO、WARN等
path="./logs"
rotationCount=3   #日志文件保存个数

[timer]
interval=600       # 周期性任务的通用执行间隔，单位：s

[http]
port=1216
logFilePath="./logs/access.log"
logFileCount=3

[db]
server = "root:1@(172.16.1.128:3306)/test?charset=utf8&parseTime=True&loc=Local&timeout=2s"
maxIdleConns = 16
maxOpenConns = 64
connMaxLifetime = 10

[jwt]
secret="Blue@1216"
expire=3600